// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBowDhIo-vkBUJB5XLfTTilWVbbxy08R6c',
    appId: '1:189945333110:web:2cdec9000c7fe56d352657',
    messagingSenderId: '189945333110',
    projectId: 'quiz-lab-dev',
    authDomain: 'quiz-lab-dev.firebaseapp.com',
    storageBucket: 'quiz-lab-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF6qK4B-m8CeAR5RyGXYiednYsM09gMLk',
    appId: '1:189945333110:android:57112705f99d769a352657',
    messagingSenderId: '189945333110',
    projectId: 'quiz-lab-dev',
    storageBucket: 'quiz-lab-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVRPV7LroSFug7yyx-sejMjxbsRy1cglA',
    appId: '1:189945333110:ios:d21f6952398f919a352657',
    messagingSenderId: '189945333110',
    projectId: 'quiz-lab-dev',
    storageBucket: 'quiz-lab-dev.appspot.com',
    iosClientId: '189945333110-3oh713d6f2hrfv1utt6s6g0megik9pqa.apps.googleusercontent.com',
    iosBundleId: 'gabriel.guimaraes.quizLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVRPV7LroSFug7yyx-sejMjxbsRy1cglA',
    appId: '1:189945333110:ios:d21f6952398f919a352657',
    messagingSenderId: '189945333110',
    projectId: 'quiz-lab-dev',
    storageBucket: 'quiz-lab-dev.appspot.com',
    iosClientId: '189945333110-3oh713d6f2hrfv1utt6s6g0megik9pqa.apps.googleusercontent.com',
    iosBundleId: 'gabriel.guimaraes.quizLab',
  );
}
