// Generated by spider on 2022-07-10 11:45:17.039148

class Images {
  Images._();

  static const String appIconIconOnly = 'assets/images/app_icon_icon_only.png';

  static const List<String> values = [appIconIconOnly];
}
