// coverage:ignore-file
// Generated by spider on 2022-08-23 00:39:38.005316

class Images {
  Images._();

  static const String appIconIconOnly = 'assets/images/app_icon_icon_only.png';
  static const String forklift = 'assets/images/forklift.png';

  static const List<String> values = [appIconIconOnly, forklift];
}
