name: 'Analyze and test code'
env:
  FLUTTER_VERSION: "3.18.0-0.2.pre"
'on':
  pull_request:
    branches:
      - develop
      - master
      - feature/*
      - release/*
jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true

      - name: Get packages
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run unit tests with coverage
        run: flutter test --coverage

      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 80
          exclude: '**/widgets/**/*.dart **/design_system/**/*.dart **/generated/** **/main.dart'
