name: 'Analyze and test code'
env:
  FLUTTER_VERSION: "3.10.6"
'on':
  pull_request:
    branches:
      - develop
      - master
      - feature/*
      - release/*
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION

      - name: Get packages
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run unit tests with coverage
        run: flutter test --coverage

      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 50
          exclude: '**/widgets/**/*.dart' '**/generated/**' '**/main.dart'