name: 'Analyze and test code'
env:
  FLUTTER_VERSION: "3.7.10"
'on':
  pull_request:
    branches:
      - develop
      - master
      - feature/*
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION
      - name: Get packages
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Check Coverage Percentage
        run: flutter pub run coverde check ${{ vars.MININUM_TEST_COVERAGE }}
